inject:
  head:
    - <link rel="stylesheet" href="/css/waves.css">
    # - <link rel="stylesheet" href="/css/movie-card.css">

# 启用图片预览功能
# medium_zoom: true
# fancybox: false  # 两者任选其一              # 延迟加载时间